services:
  api:
    image: node:jod-slim # Versao usada no desenvolvimento: v22.15.0
    working_dir: /usr/src/app
    container_name: metacloud_cdn_api
    restart: unless-stopped
    ports:
      - "9710:80"
    command: npm run dev
    volumes:
      - ./api:/usr/src/app
    extra_hosts:
      - "postgres-host:host-gateway" # Informar o host do postgres
    networks:
     - metacloud-cdn-shared-net
  minio:
    image: "minio/minio:RELEASE.2025-04-08T15-41-24Z"
    container_name: metacloud_cdn_minio
    restart: unless-stopped
    ports:
      - "9711:9000" # Porta da API S3
      - "9712:9001" # Porta do Console Web
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - metacloud-cdn-shared-net
    # Comando para iniciar MinIO standalone no diretório /data
    command: server /data --console-address ":9001" 
    
    # Comando para iniciar MinIO em cluster com outros nós
    # Apontar para os outros servicos do MinIO em suas respectivas portas e diretorios
    # command: server --console-address ":9001" "http://minio1:9000/data" "http://minio2:9000/data"

networks:
  metacloud-cdn-shared-net:
    driver: bridge